---
language: python
dist: xenial 
python:
    #- "3.6"
    - "3.7"
# consider docker
install:
    - make
    - pip install nose2
    # interim ss2 until issue  #616 resolution
    - git clone https://github.com/cherusk/pyroute2.git
    - cd pyroute2; python3 setup.py install; cd ..
    ### 
    - python3 setup.py install
jobs:
  include:
     - stage: Testing
       script: 
           - make test
           - timeout 10 prometheus_ss_exporter -c ./cnfg.yml; exit 0
     - stage: Publish
       script: 'echo Commencing'
       #deploy:
         #provider: pypi
           #user: "Your username"
           #password: "Your password"
         #provider: releases
           #api_key: "GITHUB OAUTH TOKEN"
           #file: "FILE TO UPLOAD"
stages:
    - name: Testing
      if: branch = devel 
    - name: Publish
      if: branch = master

