---
language: python
dist: xenial 
python:
    #- "3.6"
    - "3.7"
# consider docker
install:
    - make
    - pip install nose2
    - python3 setup.py install
jobs:
  include:
     - stage: Testing
       script: 
           - make test
           - prometheus_ss_exporter
     - stage: Publish
       script: 'echo Commencing'
       #deploy:
         #provider: pypi
           #user: "Your username"
           #password: "Your password"
         #provider: releases
           #api_key: "GITHUB OAUTH TOKEN"
           #file: "FILE TO UPLOAD"
stages:
    - name: Testing
      if: branch = devel 
    - name: Publish
      if: branch = master

